=== simondolk/algquiz/schemas/category.schema.json
{
  "$id": "https://example.org/schemas/category.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "id",
    "name",
    "speciesIds"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string"
    },
    "speciesIds": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "additionalProperties": true
}

=== simondolk/algquiz/data/categories/svampar.json
{
  "id": "svampar",
  "name": "Bra svampar att känna till",
  "description": "Urval av bra matsvampar och några giftiga",
  "speciesIds": [
  "trollsmor",
  "stenmurkla",
  "monjeskal",
  "vartig-roksvamp",
  "skalroksvamp",
  "blek-taggsvamp",
  "rodgul-taggsvamp",
  "en-gul-fingersvamp",
  "druvfingersvamp",
  "gullhorn",
  "blomkalssvamp",
  "kantarell",
  "blek-kantarell",
  "narrkantarell",
  "trattkantarell",
  "rodgul-trumpetsvamp",
  "svart-trumpetsvamp",
  "porer-av-orsopp",
  "svavelticka",
  "farticka",
  "tegelsopp",
  "aspsopp",
  "bjorksopp",
  "smorsopp",
  "grynsopp",
  "sandsopp",
  "brunsopp",
  "stensopp",
  "gul-svampsnylting",
  "gallsopp",
  "tegelkremla",
  "vinkremla",
  "gulkremla",
  "giftkremla",
  "gulmjolkig-ekriska",
  "granblodriska",
  "tallblodriska",
  "skaggriska",
  "vit-flugsvamp",
  "lomsk-flugsvamp",
  "rod-flugsvamp",
  "brun-kamskivling",
  "stolt-fjallskivling",
  "honungsskivling",
  "scharlakansrod-vaxskivling",
  "sotvaxskivling",
  "kastanjemusseron",
  "riddarmusseron",
  "dropptrattskivling",
  "gifttrattskivling",
  "en-spindelskivling",
  "rynkad-tofsskivling",
  "tuvspindelskivling",
  "bockspindelskivling",
  "toppig-giftspindelskivling",
  "rodskivig-kanelspindelskivling",
  "pluggskivling",
  "snobollschampinjon",
  "kungschampinjon",
  "karbolchampinjon",
  "fjallig-blacksvamp",
  "gra-blacksvamp",
  "citrongul-slemskivling",
  "rokSlojskivling",
  "en-hatta",
  "gra-brokskivling",
  "stubb-blacksvamp",
  "eksopp",
  "sillkremla"
]
}

=== simondolk/algquiz/data/categories/faglar-sodra-sverige.json
{
  "id": "faglar-sodra-sverige",
  "name": "Fåglar man bör kunna i södra Sverige",
  "description": "Några utvalda arter man bara måste kunna i södra Sverige",
  "speciesIds": [
    "parus-major",
    "cyanistes-caeruleus",
    "sitta-europaea",
    "passer-montanus",
    "passer-domesticus",
    "pyrrhula-pyrrhula",
    "chloris-chloris",
    "fringilla-coelebs",
    "fringilla-montifringilla",
    "dendrocopos-major",
    "turdus-merula",
    "erithacus-rubecula",
    "spinus-spinus",
    "carduelis-carduelis",
    "coccothraustes-coccothraustes",
    "poecile-palustris",
    "poecile-montanus",
    "periparus-ater",
    "lophophanes-cristatus",
    "aegithalos-caudatus",
    "emberiza-citrinella",
    "garrulus-glandarius",
    "pica-pica",
    "coloeus-monedula",
    "turdus-pilaris",
    "acanthis-flammea",
    "streptopelia-decaocto",
    "prunella-modularis",
    "certhia-familiaris",
    "picus-viridis"
  ]
}

=== simondolk/algquiz/data/categories/insekter-skog-syd.json
{
  "id": "insekter-skog-syd",
  "name": "Vanliga insekter i skog södra Sverige",
  "description": "50 vanliga arter kopplade till skogsmiljöer i södra Sverige.",
  "speciesIds": [
    "ips-typographus",
    "tomicus-piniperda",
    "carabus-nemoralis",
    "monochamus-sutor",
    "chrysolina-fastuosa",
    "otiorhynchus-sulcatus",
    "gnorimus-variabilis",
    "staphylinus-olens",
    "agriotes-lineatus",
    "melolontha-melolontha",
    "dytiscus-marginalis",
    "cis-boleti",
    "aglais-urticae",
    "gonepteryx-rhamni",
    "polygonia-c-album",
    "pieris-brassicae",
    "melitaea-athalia",
    "operophtera-brumata",
    "autographa-gamma",
    "apatura-iris",
    "aglais-io",
    "argynnis-aglaja",
    "musca-domestica",
    "lipoptena-cervi",
    "hypoderma-bovis",
    "culex-pipiens",
    "lucilia-sericata",
    "syrphus-ribesii",
    "tabanus-bromius",
    "mycetophila-fungorum",
    "apis-mellifera",
    "vespula-vulgaris",
    "formica-rufa",
    "ichneumon-suspiciosus",
    "bombus-terrestris",
    "dolichovespula-saxonica",
    "formica-fusca",
    "palomena-prasina",
    "lygaeus-equestris",
    "philaenus-spumarius",
    "cicadella-viridis",
    "gerris-lacustris",
    "chorthippus-parallelus",
    "coenagrion-puella",
    "aeshna-grandis",
    "ephemera-vulgata",
    "nemoura-cinerea",
    "limnephilus-flavicornis",
    "forficula-auricularia",
    "lepisma-saccharinum"
  ]
}

=== simondolk/algquiz/data/categories/faglar-fagelbord.json
{
  "id": "faglar-fagelbord",
  "name": "Vanliga fåglar runt fågelbordet",
  "description": "30 vanliga fågelarter man kan se runt fågelbordet",
  "speciesIds": [
    "parus-major",
    "cyanistes-caeruleus",
    "sitta-europaea",
    "passer-montanus",
    "passer-domesticus",
    "pyrrhula-pyrrhula",
    "chloris-chloris",
    "fringilla-coelebs",
    "fringilla-montifringilla",
    "dendrocopos-major",
    "turdus-merula",
    "erithacus-rubecula",
    "spinus-spinus",
    "carduelis-carduelis",
    "coccothraustes-coccothraustes",
    "poecile-palustris",
    "poecile-montanus",
    "periparus-ater",
    "lophophanes-cristatus",
    "aegithalos-caudatus",
    "emberiza-citrinella",
    "garrulus-glandarius",
    "pica-pica",
    "coloeus-monedula",
    "turdus-pilaris",
    "acanthis-flammea",
    "streptopelia-decaocto",
    "prunella-modularis",
    "certhia-familiaris",
    "picus-viridis"
  ]
}

=== simondolk/algquiz/data/categories/insekter-syd.json
{
  "id": "insekter-syd",
  "name": "Vanliga insekter i södra Sverige",
  "description": "Urval av arter typiska för södra Sverige",
  "speciesIds": [
    "apis-mellifera",
    "bombus-terrestris",
    "vespula-vulgaris",
    "dolichovespula-rufa",
    "formica-rufa",
    "lasius-niger",
    "musca-domestica",
    "tabanus-bovinus",
    "simuliidae",
    "culex-pipiens",
    "coccinella-septempunctata",
    "carabus-nemoralis",
    "geotrupes-stercorarius",
    "melolontha-melolontha",
    "cetonia-aurata",
    "aglais-urticae",
    "aglais-io",
    "gonepteryx-rhamni",
    "pieris-brassicae",
    "polygonia-c-album",
    "dolycoris-baccarum",
    "lygaeidae",
    "aphididae",
    "chorthippus-brunneus",
    "gryllus-campestris",
    "forficula-auricularia",
    "lepisma-saccharinum",
    "philaenus-spumarius",
    "gerris-lacustris",
    "tettigonia-viridissima"
  ]
}

=== simondolk/algquiz/data/categories/alger-syd.json
{
  "id": "alger-syd",
  "name": "Vanliga alger i södra Sverige",
  "description": "Urval av arter typiska för södra Sverige",
  "speciesIds": [
    "fucus-vesiculosus",
    "fucus-serratus",
    "fucus-spiralis",
    "ascophyllum-nodosum",
    "laminaria-hyperborea",
    "laminaria-digitata",
    "saccharina-latissima",
    "himanthalia-elongata",
    "chorda-filum",
    "halidrys-siliquosa",
    "elachista-fucicola",
    "sphacelaria-cirrosa",
    "sargassum-muticum",
    "ulva-lactuca",
    "ulva-intestinalis",
    "cladophora-glomerata",
    "bryopsis-plumosa",
    "corallina-officinalis",
    "furcellaria-lumbricalis",
    "polysiphonia-spp",
    "polysiphonia-elongata",
    "ceramium-tenuicorne",
    "rhodomela-confervoides",
    "palmaria-palmata",
    "chondrus-crispus",
    "delesseria-sanguinea",
    "polyides-rotunda"
  ]
}
