=== simondolk/algquiz/schemas/species.schema.json
{
  "$id": "https://example.org/schemas/species.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "id",
    "latinName",
    "images"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "commonName": {
      "type": "string"
    },
    "latinName": {
      "type": "string",
      "minLength": 1
    },
    "group": {
      "type": "string"
    },
    "subgroup": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "images": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": true
}

=== simondolk/algquiz/data/species/index.json
[
  {
    "id": "aglais-io",
    "commonName": "påfågelöga",
    "latinName": "Aglais io",
    "group": "Insekter",
    "subgroup": "Fjärilar",
    "aliases": [
      "påfågelöga",
      "Aglais io"
    ],
    "images": [
      "images/pafageloga.jpg"
    ]
  },
  {
  "id": "operophtera-brumata",
  "commonName": "mindre frostfjäril",
  "latinName": "Operophtera brumata",
  "group": "Insekter",
  "subgroup": "Fjärilar",
  "aliases": [
    "mindre frostfjäril",
    "frostfjäril",
    "allmän frostfjäril",
    "Operophtera brumata"
  ],
  "images": [
    "images/mindre_frostfjaril.jpg"
  ]
},
  {
  "id": "autographa-gamma",
  "commonName": "gammafly",
  "latinName": "Autographa gamma",
  "group": "Insekter",
  "subgroup": "Fjärilar",
  "aliases": [
    "gammafly",
    "Autographa gamma",
    "silver Y"
  ],
  "images": [
    "images/gammafly.jpg"
  ]
},
  {
  "id": "argynnis-aglaja",
  "commonName": "ängspärlemorfjäril",
  "latinName": "Argynnis aglaja",
  "group": "Insekter",
  "subgroup": "Fjärilar",
  "aliases": [
    "ängspärlemorfjäril",
    "stor pärlemorfjäril",
    "Argynnis aglaja",
    "Speyeria aglaja"
  ],
  "images": [
    "images/angsparlemorfjaril.jpg"
  ]
},
  {
    "id": "aglais-urticae",
    "commonName": "nässelfjäril",
    "latinName": "Aglais urticae",
    "group": "Insekter",
    "subgroup": "Fjärilar",
    "aliases": [
      "nässelfjäril",
      "Aglais urticae"
    ],
    "images": [
      "images/nasselfjaril.jpg"
    ]
  },
  {
    "id": "aphididae",
    "commonName": "bladlus",
    "latinName": "Aphididae",
    "group": "Insekter",
    "subgroup": "Halvvingar",
    "aliases": [
      "Aphididae",
      "bladlus",
      "bladlöss"
    ],
    "images": [
      "images/bladlus.jpg"
    ]
  },
  {
    "id": "apis-mellifera",
    "commonName": "honungsbi",
    "latinName": "Apis mellifera",
    "group": "Insekter",
    "subgroup": "Steklar",
    "aliases": [
      "honungsbi",
      "Apis mellifera",
      "bi"
    ],
    "images": [
      "images/honungsbi.jpg"
    ]
  },
  {
    "id": "ascophyllum-nodosum",
    "commonName": "Knöltång",
    "latinName": "Ascophyllum nodosum",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Knöltång",
      "Ascophyllum nodosum",
      "knoltang"
    ],
    "images": [
      "images/knoltang_1.jpg",
      "images/knoltang_2.jpg",
      "images/knoltang_3.jpg",
      "images/knoltang_4.jpg"
    ]
  },
  {
    "id": "bombus-terrestris",
    "commonName": "mörk jordhumla",
    "latinName": "Bombus terrestris",
    "group": "Insekter",
    "subgroup": "Steklar",
    "aliases": [
      "mörk jordhumla",
      "jordhumla",
      "Bombus",
      "Bombus terrestris"
    ],
    "images": [
      "images/jordhumla.jpg"
    ]
  },
  {
    "id": "bryopsis-plumosa",
    "commonName": "Grönplym",
    "latinName": "Bryopsis plumosa",
    "group": "Alger",
    "subgroup": "Grönalger",
    "aliases": [
      "Grönplym",
      "Bryopsis plumosa",
      "gronplym"
    ],
    "images": [
      "images/gronplym_1.jpg",
      "images/gronplym_2.jpg",
      "images/gronplym_3.jpg",
      "images/gronplym_4.jpg"
    ]
  },
  {
    "id": "carabus-nemoralis",
    "commonName": "jordlöpare",
    "latinName": "Carabus nemoralis",
    "group": "Insekter",
    "subgroup": "Skalbaggar",
    "aliases": [
      "jordlöpare",
      "Carabus nemoralis"
    ],
    "images": [
      "images/jordlopare.jpg"
    ]
  },
  {
    "id": "ceramium-tenuicorne",
    "commonName": "Ullsläke",
    "latinName": "Ceramium tenuicorne",
    "group": "Alger",
    "subgroup": "Rödalger",
    "aliases": [
      "Ullsläke",
      "Ceramium tenuicorne",
      "ullslake"
    ],
    "images": [
      "images/ullslake_1.jpg",
      "images/ullslake_2.jpg",
      "images/ullslake_3.jpg",
      "images/ullslake_4.jpg"
    ]
  },
  {
    "id": "cetonia-aurata",
    "commonName": "blomsterbagge",
    "latinName": "Cetonia aurata",
    "group": "Insekter",
    "subgroup": "Skalbaggar",
    "aliases": [
      "blomsterbagge",
      "Cetonia aurata",
      "guldbagge"
    ],
    "images": [
      "images/blomsterbagge.jpg"
    ]
  },
  {
    "id": "chondrus-crispus",
    "commonName": "Karragenalg",
    "latinName": "Chondrus crispus",
    "group": "Alger",
    "subgroup": "Rödalger",
    "aliases": [
      "Karragenalg",
      "Chondrus crispus",
      "karragentang",
      "irlandsk mossa"
    ],
    "images": [
      "images/karragenalg_1.jpg",
      "images/karragenalg_2.jpg",
      "images/karragenalg_3.jpg",
      "images/karragenalg_4.jpg"
    ]
  },
  {
    "id": "chorda-filum",
    "commonName": "Sudare",
    "latinName": "Chorda filum",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Sudare",
      "Chorda filum",
      "snarjtang",
      "snärjtång"
    ],
    "images": [
      "images/sudare_1.jpg",
      "images/sudare_2.jpg",
      "images/sudare_3.jpg",
      "images/sudare_4.jpg"
    ]
  },
  {
    "id": "chorthippus-brunneus",
    "commonName": "backgräshoppa",
    "latinName": "Chorthippus brunneus",
    "group": "Insekter",
    "subgroup": "Hopprätvingar",
    "aliases": [
      "backgräshoppa",
      "Chorthippus brunneus"
    ],
    "images": [
      "images/backgrashoppa.jpg"
    ]
  },
  {
    "id": "cladophora-glomerata",
    "commonName": "Grönslick",
    "latinName": "Cladophora glomerata",
    "group": "Alger",
    "subgroup": "Grönalger",
    "aliases": [
      "Grönslick",
      "Cladophora glomerata",
      "gronslick"
    ],
    "images": [
      "images/gronslick_1.jpg",
      "images/gronslick_2.jpg",
      "images/gronslick_3.jpg",
      "images/gronslick_4.jpg"
    ]
  },
  {
    "id": "coccinella-septempunctata",
    "commonName": "sjuprickig nyceklpiga",
    "latinName": "Coccinella septempunctata",
    "group": "Insekter",
    "subgroup": "Skalbaggar",
    "aliases": [
      "sjuprickig nyckelpiga",
      "Coccinella septempunctata"
    ],
    "images": [
      "images/sjuprickig_nyckelpiga.jpg"
    ]
  },
  {
    "id": "corallina-officinalis",
    "commonName": "Korallalg",
    "latinName": "Corallina officinalis",
    "group": "Alger",
    "subgroup": "Rödalger",
    "aliases": [
      "Korallalg",
      "Corallina officinalis"
    ],
    "images": [
      "images/korallalg_1.jpg",
      "images/korallalg_2.jpg",
      "images/korallalg_3.jpg",
      "images/korallalg_4.jpg"
    ]
  },
  {
    "id": "culex-pipiens",
    "commonName": "sydlig husmygga",
    "latinName": "Culex pipiens",
    "group": "Insekter",
    "subgroup": "Tvåvingar",
    "aliases": [
      "sydlig husmygga",
      "husmygga",
      "Culex pipiens"
    ],
    "images": [
      "images/husmygga.jpg"
    ]
  },
  {
    "id": "delesseria-sanguinea",
    "commonName": "Ribbeblad",
    "latinName": "Delesseria sanguinea",
    "group": "Alger",
    "subgroup": "Rödalger",
    "aliases": [
      "Ribbeblad",
      "Delesseria sanguinea",
      "nervtang"
    ],
    "images": [
      "images/ribbeblad_1.jpg",
      "images/ribbeblad_2.jpg",
      "images/ribbeblad_3.jpg",
      "images/ribbeblad_4.jpg"
    ]
  },
  {
    "id": "dolichovespula-rufa",
    "commonName": "rödhalsad geting",
    "latinName": "Vespula rufa",
    "group": "Insekter",
    "subgroup": "Steklar",
    "aliases": [
      "Vespula rufa",
      "rödbandad geting",
      "rödhalsad geting"
    ],
    "images": [
      "images/rodhalsad-geting.jpg"
    ]
  },
  {
    "id": "elachista-fucicola",
    "commonName": "Tångludd",
    "latinName": "Elachista fucicola",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Tångludd",
      "Elachista fucicola",
      "tangludd"
    ],
    "images": [
      "images/tangludd_1.jpg",
      "images/tangludd_2.jpg",
      "images/tangludd_3.jpg",
      "images/tangludd_4.jpg"
    ]
  },
  {
    "id": "forficula-auricularia",
    "commonName": "vanlig tvestjärt",
    "latinName": "Forficula auricularia",
    "group": "Insekter",
    "subgroup": "Övriga vanliga arter",
    "aliases": [
      "tvestjärt",
      "vanlig tvestjärt",
      "Forficula auricularia"
    ],
    "images": [
      "images/tvestjart.jpg"
    ]
  },
  {
    "id": "formica-rufa",
    "commonName": "röd skogsmyra",
    "latinName": "Formica rufa",
    "group": "Insekter",
    "subgroup": "Steklar",
    "aliases": [
      "skogsmyra",
      "Formica rufa",
      "röd skogsmyra"
    ],
    "images": [
      "images/rod-skogsmyra.jpg"
    ]
  },
  {
    "id": "fucus-serratus",
    "commonName": "Sågtång",
    "latinName": "Fucus serratus",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Sågtång",
      "Fucus serratus",
      "sagtang"
    ],
    "images": [
      "images/sagtang_1.jpg",
      "images/sagtang_2.jpg",
      "images/sagtang_3.jpg",
      "images/sagtang_4.jpg"
    ]
  },
  {
    "id": "fucus-spiralis",
    "commonName": "Spiraltång",
    "latinName": "Fucus spiralis",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Spiraltång",
      "Fucus spiralis",
      "spiraltang"
    ],
    "images": [
      "images/spiraltang_1.jpg",
      "images/spiraltang_2.jpg",
      "images/spiraltang_3.jpg",
      "images/spiraltang_4.jpg"
    ]
  },
  {
    "id": "fucus-vesiculosus",
    "commonName": "Blåstång",
    "latinName": "Fucus vesiculosus",
    "group": "Alger",
    "subgroup": "Brunalger",
    "aliases": [
      "Blåstång",
      "Fucus vesiculosus",
      "blastang"
    ],
    "images": [
      "images/blastang_1.jpg",
      "images/blastang_2.jpg",
      "images/blastang_3.jpg",
      "images/blastang_4.jpg"
    ]
  },
  {
    "id": "furcellaria-lumbricalis",
    "commonName": "Kräkel",
    "latinName": "Furcellaria lumbricalis",
    "group": "Alger",
    "subgroup": "Rödalger",
    "aliases": [
      "Kräkel",
      "Furcellaria lumbricalis",
      "gaffeltang"
    ],
    "images": [
      "images/krakel_1.jpg",
      "images/krakel_2.jpg",
      "images/krakel_3.jpg",
      "images/krakel_4.jpg"
    ]
  },
  {
